
@baseUrl = http://localhost:3000
@contentType = application/json

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyMDI0MzRjLTJjYWEtNDlkMC1hZTVhLWUxYzlkOTRiMzkwYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3Njk1NzM2NiwiZXhwIjoxNzc3NTYyMTY2fQ.wLmSF0byIjJx5ZddphF8piz50bShDX7sbYSWAeOJrTA

@doctorId = f7a0d86e-89e9-466f-986c-19e8e2c8cfe2

### GET PENDING DOCTORS
GET {{baseUrl}}/admin/doctors?status=PENDING
Authorization: Bearer {{adminToken}}
#Respone
# [
#   {
#     "id": "eea769d5-7a7b-4696-b31b-f50f93a43d66",
#     "userId": "f834b563-af2b-4b46-ad90-d94703dad30b",
#     "specialization": "CARDIOLOGIST",
#     "fees": 50,
#     "documentUrl": "https://example.com/license.pdf",
#     "status": "PENDING",
#     "rejectionReason": null,
#     "createdAt": "2026-04-22T09:00:15.747Z",
#     "updatedAt": "2026-04-22T09:10:38.510Z",
#     "user": {
#       "id": "f834b563-af2b-4b46-ad90-d94703dad30b",
#       "name": "Dr Ahmed",
#       "email": "doctor@test.com",
#       "password": "$2b$10$ScI.Z0TzEJc75H1HvZ2qwOTBHMX7gePienD93VGNerQsD6sWIGbtS",
#       "role": "DOCTOR",
#       "createdAt": "2026-04-22T09:00:15.501Z",
#       "updatedAt": "2026-04-22T09:00:15.501Z"
#     }
#   }
# ]

### GET ALL DOCTORS
GET {{baseUrl}}/admin/doctors
Authorization: Bearer {{adminToken}}
#Response
# [
#   {
#     "id": "1abcf988-d397-402a-82c8-32d3f4874c93",
#     "userId": "5427b5d5-b1bf-442e-ba2d-9eb604bcf2f7",
#     "specialization": "NEUROLOGIST",
#     "fees": 50,
#     "documentUrl": "https://excalidraw.com/",
#     "status": "APPROVED",
#     "rejectionReason": null,
#     "createdAt": "2026-04-22T09:36:07.954Z",
#     "updatedAt": "2026-04-22T09:38:23.198Z",
#     "user": {
#       "id": "5427b5d5-b1bf-442e-ba2d-9eb604bcf2f7",
#       "name": "Test User",
#       "email": "test123@gmail.com",
#       "password": "$2b$10$xB.Rcr4BbSbpI93yJo.VueAI2A2EULCns9tVB0OocdLBIXx33T3B.",
#       "role": "DOCTOR",
#       "createdAt": "2026-04-22T09:36:07.699Z",
#       "updatedAt": "2026-04-22T09:36:07.699Z"
#     }
#   },
#   {
#     "id": "eea769d5-7a7b-4696-b31b-f50f93a43d66",
#     "userId": "f834b563-af2b-4b46-ad90-d94703dad30b",
#     "specialization": "CARDIOLOGIST",
#     "fees": 50,
#     "documentUrl": "https://example.com/license.pdf",
#     "status": "PENDING",
#     "rejectionReason": null,
#     "createdAt": "2026-04-22T09:00:15.747Z",
#     "updatedAt": "2026-04-22T09:10:38.510Z",
#     "user": {
#       "id": "f834b563-af2b-4b46-ad90-d94703dad30b",
#       "name": "Dr Ahmed",
#       "email": "doctor@test.com",
#       "password": "$2b$10$ScI.Z0TzEJc75H1HvZ2qwOTBHMX7gePienD93VGNerQsD6sWIGbtS",
#       "role": "DOCTOR",
#       "createdAt": "2026-04-22T09:00:15.501Z",
#       "updatedAt": "2026-04-22T09:00:15.501Z"
#     }
#   }
# ]

### GET SINGLE DOCTOR
GET {{baseUrl}}/admin/doctors/{{doctorId}}
Authorization: Bearer {{adminToken}}

### APPROVE
PATCH {{baseUrl}}/admin/doctors/{{doctorId}}/approve
Authorization: Bearer {{adminToken}}

### REJECT
PATCH {{baseUrl}}/admin/doctors/{{doctorId}}/reject
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "reason": "Invalid documents"
}