### =========================
### VARIABLES
### =========================
@baseUrl = http://localhost:3000
@contentType = application/json


### =========================
### REGISTER PATIENT
### =========================
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "name": "Ali",
  "email": "ali@test.com",
  "password": "password123",
  "role": "PATIENT"
}


### =========================
### LOGIN PATIENT
### =========================
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "hassamata2@gmail.com",
  "password": "123456"
}


### =========================
### REGISTER DOCTOR
### =========================
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "name": "Dr Ahmed",
  "email": "doctor@test.com",
  "password": "123456",
  "role": "DOCTOR"
}


### =========================
### LOGIN DOCTOR
### =========================
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "hassamata86@gmail.com",
  "password": "123456"
}

# Response
# {
#   "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY4MzRiNTYzLWFmMmItNGI0Ni1hZDkwLWQ5NDcwM2RhZDMwYiIsInJvbGUiOiJET0NUT1IiLCJpYXQiOjE3NzY4NDg2NDUsImV4cCI6MTc3NzQ1MzQ0NX0.czVzP-GQ9oXv1wdgdcFnUJDK6xx6vwB6glaU8KKaluc",
#   "role": "DOCTOR",
#   "doctorStatus": "PENDING"
# }

### =========================
### VALIDATE TOKEN
### =========================
POST {{baseUrl}}/auth/validate
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlZTYzOTg3LTQ1NjYtNDM2NC1iZjNmLTcxZjVlZjM2YWU5ZiIsInJvbGUiOiJET0NUT1IiLCJpYXQiOjE3NzY2Nzc5OTQsImV4cCI6MTc3NzI4Mjc5NH0.lfa3f8f5sfFIwSjm3TE89Qm1X5VO3FCmbq4vuCHPdAg