### =========================
### VARIABLES
### =========================
@baseUrl = http://localhost:3000
@contentType = application/json

@doctorToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlZTYzOTg3LTQ1NjYtNDM2NC1iZjNmLTcxZjVlZjM2YWU5ZiIsInJvbGUiOiJET0NUT1IiLCJpYXQiOjE3NzY1NDM2NTksImV4cCI6MTc3NzE0ODQ1OX0.WdKEu9SNS0EfBseRIDv4R1B0w755GTAONFzq6g2wSkE
@doctorId = 0e1c4466-fa7c-4d16-b38c-79990260348b
@availabilityId = <AVAILABILITY_ID>


### =========================
### ADD AVAILABILITY (DOCTOR)
### =========================
POST {{baseUrl}}/doctor/availability
Content-Type: {{contentType}}
Authorization: Bearer {{doctorToken}}

{
  "day": "TUESDAY",
  "startTime": "2026-04-21T09:00:00.000Z",
  "endTime": "2026-04-21T12:00:00.000Z"
}


### =========================
### ADD SECOND SLOT (VALID)
### =========================
POST {{baseUrl}}/doctor/availability
Content-Type: {{contentType}}
Authorization: Bearer {{doctorToken}}

{
  "day": "WEDNESDAY",
  "startTime": "2026-05-20T13:00:00.000Z",
  "endTime": "2026-05-20T16:00:00.000Z"
}


### =========================
### GET MY AVAILABILITY (DOCTOR)
### =========================
GET {{baseUrl}}/doctor/availability/me
Authorization: Bearer {{doctorToken}}

# Response
# [
#   {
#     "id": "fd007774-8253-4288-939d-e4d3f43bff4c",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "MONDAY",
#     "startTime": "2026-04-20T09:00:00.000Z",
#     "endTime": "2026-04-20T12:00:00.000Z",
#     "createdAt": "2026-04-18T20:23:54.380Z"
#   },
#   {
#     "id": "4ceba005-6389-4a4d-a53d-6c533bc9abbc",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "MONDAY",
#     "startTime": "2026-04-20T13:00:00.000Z",
#     "endTime": "2026-04-20T16:00:00.000Z",
#     "createdAt": "2026-04-18T20:24:18.267Z"
#   },
#   {
#     "id": "5310df94-c2f4-4ae6-a2da-41d5d17141b7",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "TUESDAY",
#     "startTime": "2026-04-21T09:00:00.000Z",
#     "endTime": "2026-04-21T12:00:00.000Z",
#     "createdAt": "2026-04-20T11:44:51.626Z"
#   },
#   {
#     "id": "c2b532b4-3589-44ce-b3b3-414b5deb1dec",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "WEDNESDAY",
#     "startTime": "2026-05-20T13:00:00.000Z",
#     "endTime": "2026-05-20T16:00:00.000Z",
#     "createdAt": "2026-04-20T11:46:28.818Z"
#   }
# ]


### =========================
### GET DOCTOR AVAILABILITY (PUBLIC)
### =========================
# GET {{baseUrl}}/doctor/availability/{{doctorId}}
# [
#   {
#     "id": "fd007774-8253-4288-939d-e4d3f43bff4c",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "MONDAY",
#     "startTime": "2026-04-20T09:00:00.000Z",
#     "endTime": "2026-04-20T12:00:00.000Z",
#     "createdAt": "2026-04-18T20:23:54.380Z"
#   },
#   {
#     "id": "4ceba005-6389-4a4d-a53d-6c533bc9abbc",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "MONDAY",
#     "startTime": "2026-04-20T13:00:00.000Z",
#     "endTime": "2026-04-20T16:00:00.000Z",
#     "createdAt": "2026-04-18T20:24:18.267Z"
#   },
#   {
#     "id": "5310df94-c2f4-4ae6-a2da-41d5d17141b7",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "TUESDAY",
#     "startTime": "2026-04-21T09:00:00.000Z",
#     "endTime": "2026-04-21T12:00:00.000Z",
#     "createdAt": "2026-04-20T11:44:51.626Z"
#   },
#   {
#     "id": "c2b532b4-3589-44ce-b3b3-414b5deb1dec",
#     "doctorId": "0e1c4466-fa7c-4d16-b38c-79990260348b",
#     "day": "WEDNESDAY",
#     "startTime": "2026-05-20T13:00:00.000Z",
#     "endTime": "2026-05-20T16:00:00.000Z",
#     "createdAt": "2026-04-20T11:46:28.818Z"
#   }
# ]


### =========================
### DELETE AVAILABILITY
### =========================
DELETE {{baseUrl}}/doctor/availability/{{availabilityId}}
Authorization: Bearer {{doctorToken}}


### =========================
### OVERLAP TEST (SHOULD FAIL)
### =========================
POST {{baseUrl}}/doctor/availability
Content-Type: {{contentType}}
Authorization: Bearer {{doctorToken}}

{
  "day": "MONDAY",
  "startTime": "2026-04-20T11:00:00.000Z",
  "endTime": "2026-04-20T14:00:00.000Z"
}


### =========================
### INVALID TIME RANGE (SHOULD FAIL)
### =========================
POST {{baseUrl}}/doctor/availability
Content-Type: {{contentType}}
Authorization: Bearer {{doctorToken}}

{
  "day": "MONDAY",
  "startTime": "2026-04-20T14:00:00.000Z",
  "endTime": "2026-04-20T10:00:00.000Z"
}


### =========================
### UNAUTHORIZED TEST (SHOULD FAIL)
### =========================
POST {{baseUrl}}/doctor/availability
Content-Type: {{contentType}}

{
  "day": "MONDAY",
  "startTime": "2026-04-20T09:00:00.000Z",
  "endTime": "2026-04-20T12:00:00.000Z"
}